# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 04:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160816_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 4, 14, 31, 566883, tzinfo=utc)),
        ),
    ]
