# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160816_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='trends',
            name='html_requests',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='html_transfer_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='total_requests',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='total_transfer_size',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
