# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 06:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160816_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='trends',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 8, 30, 6, 42, 57, 383990, tzinfo=utc)),
        ),
    ]
