# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-31 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_trends_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trends',
            name='cacheable_resources',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='css_requests',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='css_transfer_size',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='date',
            field=models.DecimalField(decimal_places=0, default=1472578459000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trends',
            name='doc_size',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='dom_elements',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='domains',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='flash_requests',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='flash_transfer_size',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='font_requests',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='font_transfer_size',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='html_requests',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='html_transfer_size',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='image_requests',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='image_transfer_size',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='js_requests',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='js_transfer_size',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='max_reqs_on_1_domain',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='other_requests',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='other_transfer_size',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='tcp_connections',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='total_requests',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='trends',
            name='total_transfer_size',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
    ]
